import {
  ImagePlus,
  Lightbulb,
  Scissors,
  ShieldCheck,
  Trash2,
} from "lucide-react";
import { useEffect, useState, type ChangeEvent, type FormEvent } from "react";
import CustomerBottomNav from "../../components/customer/CustomerBottomNav";
import { usePublicTheme } from "../../hooks/usePublicTheme";
import { createAiConsultation } from "../../services/aiConsultationService";
import type {
  AiConsultation,
  ConsultationRequestType,
  StyleRecommendation,
} from "../../types/aiConsultation";
import { getApiErrorMessage } from "../../utils/apiError";
import "./customerDashboardPage.css";
import "./aiConsultationPage.css";

const types = ["image/jpeg", "image/png", "image/webp"];

const Recommendations = ({
  title,
  items,
}: {
  title: string;
  items: StyleRecommendation[];
}) =>
  !items.length ? null : (
    <section className="recommendations-section">
      <h2>{title}</h2>
      {items.map((item) => (
        <article key={item.styleName} className="recommendation-card">
          <h3>{item.styleName}</h3>
          
          {/* Render preview image generated by AI */}
          {item.previewImage && (
            <div className="recommendation-image-container">
              <img
                src={item.previewImage}
                alt={`Visual preview for ${item.styleName}`}
                className="recommendation-image"
                loading="lazy"
              />
            </div>
          )}
          {item.previewStatus === "unavailable" && (
            <p className="preview-unavailable" role="status">
              A visual preview could not be generated for this style. The barber instructions are still available below.
            </p>
          )}

          <p>{item.explanation}</p>
          <strong>Tell your barber</strong>
          <span>{item.barberInstructions}</span>
        </article>
      ))}
    </section>
  );

const AiConsultationPage = () => {
  const { brand, style } = usePublicTheme();
  const [image, setImage] = useState<File | null>(null);
  const [preview, setPreview] = useState<string | null>(null);
  const [requestType, setRequestType] =
    useState<ConsultationRequestType>("haircut");
  const [preference, setPreference] = useState("");
  const [result, setResult] = useState<AiConsultation | null>(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  useEffect(
    () => () => {
      if (preview) URL.revokeObjectURL(preview);
    },
    [preview],
  );

  const removeImage = () => {
    if (preview) URL.revokeObjectURL(preview);
    setImage(null);
    setPreview(null);
  };

  const selectImage = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    event.target.value = "";
    if (!file) return;
    if (!types.includes(file.type) || file.size > 5 * 1024 * 1024) {
      setError("Choose a JPEG, PNG, or WEBP image smaller than 5 MB.");
      return;
    }
    removeImage();
    setError("");
    setResult(null);
    setImage(file);
    setPreview(URL.createObjectURL(file));
  };

  const submit = async (event: FormEvent) => {
    event.preventDefault();
    if (!image) {
      setError("Add a clear photo before requesting recommendations.");
      return;
    }
    setLoading(true);
    setError("");
    try {
      setResult(
        (await createAiConsultation(image, requestType, preference)).data
          .consultation,
      );
    } catch (reason) {
      setError(
        getApiErrorMessage(
          reason,
          "We could not generate recommendations right now.",
        ),
      );
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="ai-consultation-page" style={style}>
      <header className="customer-dashboard_header">
        <div className="customer-dashboard_brand">
          <span>
            {brand.logoUrl ? (
              <img src={brand.logoUrl} alt={`${brand.salonName} logo`} />
            ) : (
              <Scissors />
            )}
          </span>
          <strong>{brand.salonName}</strong>
        </div>
      </header>
      <div className="ai-consultation-content">
        <p>Personalised guidance</p>
        <h1>AI hairstyle consultant</h1>
        <span>Explore style ideas to discuss with your barber.</span>
        <form onSubmit={(event) => void submit(event)}>
          <section>
            <h2>Your photo</h2>
            {preview ? (
              <div className="preview">
                <img src={preview} alt="Selected consultation photo preview" />
                <button type="button" onClick={removeImage}>
                  <Trash2 />
                  Remove photo
                </button>
              </div>
            ) : (
              <label className="upload">
                <ImagePlus />
                <b>Add a clear photo</b>
                <small>JPEG, PNG, or WEBP · up to 5 MB</small>
                <input
                  type="file"
                  accept="image/jpeg,image/png,image/webp"
                  onChange={selectImage}
                />
              </label>
            )}
          </section>
          <section>
            <h2>Consultation type</h2>
            {(
              [
                ["haircut", "Haircut"],
                ["beard", "Beard style"],
                ["both", "Haircut and beard"],
              ] as const
            ).map(([value, label]) => (
              <label className="option" key={value}>
                <input
                  type="radio"
                  checked={requestType === value}
                  onChange={() => setRequestType(value)}
                />
                <span>{label}</span>
              </label>
            ))}
            <label className="preferences">
              Preferences (optional)
              <textarea
                value={preference}
                maxLength={500}
                onChange={(event) => setPreference(event.target.value)}
                placeholder="Modern, professional, short, low maintenance, fade, textured"
              />
            </label>
          </section>
          <aside>
            <ShieldCheck />
            By submitting, you consent to sending this photo to our AI provider
            for this one-time consultation. It is not permanently stored.
          </aside>
          {error && (
            <p role="alert" className="error">
              {error}
            </p>
          )}
          <button className="submit" disabled={loading}>
            {loading ? "Creating recommendations…" : "Get recommendations"}
          </button>
        </form>
        {result && (
          <div className="results">
            <header>
              <Lightbulb />
              <h2>Styles to discuss with your barber</h2>
            </header>
            <Recommendations
              title="Haircut ideas"
              items={result.haircutRecommendations}
            />
            <Recommendations
              title="Beard style ideas"
              items={result.beardRecommendations}
            />
            <section>
              <h2>Maintenance tips</h2>
              <ul>
                {result.maintenanceTips.map((tip) => (
                  <li key={tip}>{tip}</li>
                ))}
              </ul>
            </section>
            <p>{result.disclaimer}</p>
          </div>
        )}
      </div>
      <CustomerBottomNav active="consultation" />
    </main>
  );
};

export default AiConsultationPage;
